name: Health check

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: health check
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://fullstack-blog-hld8.onrender.com/health
