name: Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  tag_release:
    needs: [main_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && contains( join(github.event.commits.*.message, ', '), '#skip' ) == false }}
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  main_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies for backend and frontend
        run: |
          npm install
          cd frontend && npm install

      - name: Lint backend
        run: npm run lint

      - name: Lint frontend
        run: cd frontend && npm run lint

      - name: Test backend
        run: npm run test
        env:
          TEST_MONGODB_URI: ${{ secrets.TESTING_URI }}
          SECRET: ${{ secrets.SECRET }}
          PORT: 3003

      - name: E2E tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./frontend
          command: npm run test:e2e
          wait-on: "http://localhost:3000, http://localhost:3003/health"
          wait-on-timeout: 30
          start: |
            npm start
            npm run test-start --prefix ..
        env:
          TEST_MONGODB_URI: ${{ secrets.TESTING_URI }}
          SECRET: ${{ secrets.SECRET }}
          BACKEND_PORT: 3003

      - name: Deploy app
        if: ${{ github.event_name == 'push' }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      - name: Job succeeded
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Job succeeded
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Job failed
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Job failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
